############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Now"
pageRef = "/now"
weight = 3

[[main]]
weight = 4
name = "Blog"
pageRef = "/blog"

[[main]]
weight = 5
name = "Notes"
pageRef = "/notes"


#[[main]]
#parent = "Pages"
#name = "Blog"
#pageRef = "/blog"

#[[main]]
#parent = "Pages"
#name = "Contact"
#pageRef = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#pageRef = "/authors"

#[[main]]
#parent = "Pages"
#name = "Categories"
#pageRef = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#pageRef = "/404"


# footer menu
#[[footer]]
#name = "About"
#pageRef = "/about"
#weight = 1

#[[footer]]
#name = "Now"
#pageRef = "/now"
#weight = 2

#[[footer]]
#name = "Blog"
#pageRef = "/blog"
#weight = 3
